version: '3'
services:
  vue3-front-common:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue3-front-common # 引用官网 nginx 镜像
    container_name: vue3-front-common
    ports:
      - 2022:80 # 宿主机可以用 127.0.0.1:8080 即可连接容器中的数据库
    # volumes: 在 Dockerfile 都已配置完
